# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - amazonlinux:2      
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    container:
      image: ${{ matrix.os }}
      volumes: 
        - ${{ contains('amazonlinux:2', matrix.os) && '/node20217:/node20217:rw,rshared' || ' ' }} 
        - ${{ contains('amazonlinux:2', matrix.os) && '/node20217:/__e/node20:ro,rshared' || ' ' }}        

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install `yum` dependencies
        run: yum install -y gcc make gzip tar openssl-devel libevent-devel wget which
        if: ${{ contains(matrix.os, 'amazonlinux') }}

      - name: Install Node.js 20 built against glibc 2.17 for GitHub Actions
        run: |
          set -ex
          which yum \
             && yum install -y wget xz
          wget https://unofficial-builds.nodejs.org/download/release/v20.9.0/node-v20.9.0-linux-x64-glibc-217.tar.xz
          tar -xf node-v20.9.0-linux-x64-glibc-217.tar.xz --strip-components 1 -C /node20217
          ldd /__e/node20/bin/node
        working-directory: /tmp/
        if: ${{ contains('amazonlinux:2', matrix.os) }}
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
